# https://taskfile.dev
# vim: ft=yaml ts=2 sw=2 et
# Copyright © 2026 Ralph Seichter
---
version: '3'

tasks:
  default:
    cmds:
      - task -l
    silent: true

  fmt:
    desc: Format project files.
    cmds:
      - go fmt

  build:
    deps: [fmt]
    desc: Build project.
    cmds:
      - go build -o scare

  install:
    deps: [build]
    desc: Install binary.
    cmds:
      - sudo install -C scare /usr/local/bin/scare

  clean:
    desc: Cleanup project directory.
    cmds:
      - go clean
